features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy"]
catboost_features=["driver_gps_accuracy","trip_distance","total_distance","driver_distance","event_hour","complete_track_record","n_requests","last_10_track_record","last_5_track_record","last_5_ride_avg_distance"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false

[catboost]
colsample_bylevel=0.19894071603389674
depth= 5
boosting_type= "Ordered"
bootstrap_type= "Bernoulli"
l2_leaf_reg= 3.0
subsample= 0.8876209234248765
grow_policy="SymmetricTree"
objective="Logloss"
