dependencies:
  - python=3.11.0
  - pip>=20
  - pip:
    - jupyter==1.0.0
    - pandas==1.5.3
    - scikit-learn==1.2.2
    - numpy==1.24.2
    - matplotlib==3.7.1
    - seaborn==0.12.2
    - black==22.12.0
    - haversine==2.8.0
    - toml==0.10.2
    - nose2==0.14.2
    - catboost==1.2.3
